version: "3.9"
services:
  nginx:
    image: charlociraptor/flashcards-nginx
    ports:
    - "80:80"
    - "443:443"
    depends_on:
    - frontend
    - backend
    - certbot
    volumes:
    - "./data/certbot/conf:/etc/letsencrypt"
    - "./data/certbot/www:/var/www/certbot"
  frontend:
    image: charlociraptor/flashcards-front
    ports:
    - "5000:5000"
    depends_on:
    - backend
  backend:
    image: charlociraptor/flashcards-back
    ports:
    - "5001:5001"
  certbot:
    image: certbot/certbot
    volumes:
    - "./data/certbot/conf:/etc/letsencrypt"
    - "./data/certbot/www:/var/www/certbot"
