name: deploy

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run unit tests
      run: scripts/test.sh
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/auto-deploy'
    steps:
    - uses: actions/checkout@v2
    - name: deploy files to aws
      uses: appleboy/scp-action@master
      with:
        host: ${{secrets.AWS_ADDRESS}}
        username: ec2-user
        key: ${{secrets.AWS_KEY}}
        source: "docker-compose.yml"
        target: "~"
    - name: build and push images
      env:
        DOCKER_PASS: ${{secrets.DOCKER_PASS}}
        DOCKER_USER: ${{secrets.DOCKER_USER}}
      run: scripts/build.sh
    - name: refresh service
      uses: fifsky/ssh-action@master
      with:
        command: |
          docker system prune -af
          docker-compose pull
          docker-compose down ||:
          docker-compose up -d
        host: ${{secrets.AWS_ADDRESS}}
        user: ec2-user
        key: ${{secrets.AWS_KEY}}
